### PR TITLE
Add HTTP status codes declared in some other RFCs.

### PR DESCRIPTION
**Pull request by Klamath233**
Hi Nils,

I like your work! I am using it for my course group project. I find the helper.js file misses some new status codes, including the "422 Unprocessable Entity" commonly for validation failures. Therefore, I add the status codes specified in other RFCs than 2616 to helper.js; for those defined by companies and not in any RFC, I do not add them.

Thanks,
Xi

### CODE REVIEW

**Comment by nknapp** [comment]
Hi Xi,

thanks for this PR. This is a great thing. It would be greate if you could add comments to each constant with references to the RFC where they are actually defined, so that people can find it more easily (like `// rfc 1234 section 1.2.3`

Would you mind adding this information? Then I'll gladly merge.

**Comment by Klamath233** [comment]
Sure, I won't mind.

**Comment by Klamath233** [comment]
Done. By the way, how can I rebuild the application with the new "helper.js"? Thanks in advance.

**Comment by nknapp** [comment]
Thanks. I'm merging the PR.

**Comment by nknapp** [comment]
Oh, and for information about overriding and adding new helpers, have a look [in the bootprint-documentation](https://github.com/nknapp/bootprint/blob/master/doc/config.md).
I can also give you push-access, if it helps. If the changes you want to make would also help the core-module, I'd rather have them there than in a customization.

**Comment by Klamath233** [comment]
Thank you Nils. I will definitely look at that. If I have some further ideas in the future, I may ask you for the push-access. Good luck!

**Comment by nknapp** [comment]
@Klamath233 I just realized that I misunderstood [your comment](https://github.com/nknapp/bootprint-swagger/pull/43#issuecomment-151319469). I have just published a new version. I did not do this from my usual machine so I hope everything works. If there are problems, just let me know. I'll fix them tonight (in about 12 hours) and publish again.

**Comment by Klamath233** [comment]
Hi Nils. I just saw your comment. I will definitely try the new version and give feedback ASAP.

**Comment by Klamath233** [comment]
It works!

**Pull request merged**
